#!/bin/bash

if [ "${#}" -lt "8" ]
then
	echo "Usage: git-send-pull-request <command> -u <username> -b <merge branch> <comment> <title> <submit branch>"
	exit 1
fi

if ! git rev-parse --abbrev-ref ${5} &> /dev/null
then
	printf "${5} is not a valid branch\n"
	exit 1
fi

if ! git rev-parse --abbrev-ref ${8} &> /dev/null
then
	printf "${8} is not a valid branch\n"
	exit 1
fi

gitpr=/opt/dev/projects/github/git-tools/git-pull-request/git-pull-request.sh

if ! [[ -x "${gitpr}" ]]
then
	printf "Unable to find pull request executable at ${gitpr}\n"
	exit 1
fi

. script-functions

save-branch

git-update-upstream-branch ${5}
git rebase ${5} ${8}
git push origin ${8} -f

${gitpr} ${1} ${2} ${3} ${4} ${5} ${6} ${7}

restore-branch