#!/bin/bash

if [[ ${#} < 1 ]]
then
	echo "Usage: git-update-upstream-branch <branch>"
	exit 1
fi

. script-functions

save-branch

git checkout "${1}"
git pull upstream "${1}"
git push origin "${1}"

restore-branch