#!/bin/bash

. color-definitions
. script-functions

github_projects_dir=/opt/dev/projects/github

repositories=(\
	liferay-portal\
	liferay-portal-ee\
	liferay-portal-ee-6.2.x\
	liferay-portal-ee-6.2.10\
	liferay-portal-ee-6.1.x\
	liferay-portal-ee-6.1.30\
	liferay-portal-ee-7.0.x\
	liferay-plugins\
	liferay-plugins-ee\
	liferay-jenkins-ee\
)

declare -A branches

branches["liferay-portal"]="master"
branches["liferay-portal-ee"]="master"
branches["liferay-portal-ee-6.1.x"]="master"
branches["liferay-portal-ee-6.1.30"]="master"
branches["liferay-portal-ee-6.2.x"]="master"
branches["liferay-portal-ee-6.2.10"]="master"
branches["liferay-portal-ee-7.0.x"]="master"
branches["liferay-plugins"]="master"
branches["liferay-plugins-ee"]="ee-6.2.x ee-6.2.10 ee-6.1.x master"
branches["liferay-jenkins-ee"]="master"

save-directory

save-branch

for repository in ${repositories[@]}
do
	read -r -a update_branches <<< "${branches[${repository}]}"

	cd ${github_projects_dir}/${repository}

	for branch in "${update_branches[@]}"
	do
		printf "\nUpdating ${github_projects_dir}/${repository} ${green}refs/heads/${branch}${nc}\n"

		git rebase --abort &> /dev/null

		clean

		execute 'git checkout ${branch}'

		execute 'git clean -d --force'

		clean

		execute 'git pull upstream ${branch}'
		execute	'git push origin ${branch}'
	done

	execute 'git checkout ${update_branches[0]}'
done

restore-directory

restore-branch