#!/bin/bash

if [ "${#}" -lt "1" ] || [ "${#}" -gt "2" ]
then
	printf "Usage: github-get <api path> [<token>]\n"
	exit 1
fi

if [ "${#}" -eq "2" ]
then
	token_parameter="--header \"Authorization: token ${2}\""
fi

eval curl --verbose --request DELETE ${token_parameter} https://api.github.com/${1}
